/* automatically generated by rust-bindgen 0.68.1 */

#[doc = " A CTA Video Identification Code (VIC)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_cta_vic {
    pub code: u8,
}
#[test]
fn bindgen_test_layout_di_cta_vic() {
    const UNINIT: ::std::mem::MaybeUninit<di_cta_vic> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<di_cta_vic>(),
        1usize,
        concat!("Size of: ", stringify!(di_cta_vic))
    );
    assert_eq!(
        ::std::mem::align_of::<di_cta_vic>(),
        1usize,
        concat!("Alignment of ", stringify!(di_cta_vic))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).code) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic),
            "::",
            stringify!(code)
        )
    );
}
pub const di_cta_vic_video_format_picture_aspect_ratio_DI_CTA_VIC_VIDEO_FORMAT_PICTURE_ASPECT_RATIO_4_3 : di_cta_vic_video_format_picture_aspect_ratio = 0 ;
pub const di_cta_vic_video_format_picture_aspect_ratio_DI_CTA_VIC_VIDEO_FORMAT_PICTURE_ASPECT_RATIO_16_9 : di_cta_vic_video_format_picture_aspect_ratio = 1 ;
pub const di_cta_vic_video_format_picture_aspect_ratio_DI_CTA_VIC_VIDEO_FORMAT_PICTURE_ASPECT_RATIO_64_27 : di_cta_vic_video_format_picture_aspect_ratio = 2 ;
pub const di_cta_vic_video_format_picture_aspect_ratio_DI_CTA_VIC_VIDEO_FORMAT_PICTURE_ASPECT_RATIO_256_135 : di_cta_vic_video_format_picture_aspect_ratio = 3 ;
#[doc = " CTA video format picture aspect ratio."]
pub type di_cta_vic_video_format_picture_aspect_ratio = ::std::os::raw::c_uint;
pub const di_cta_vic_video_format_sync_polarity_DI_CTA_VIC_VIDEO_FORMAT_SYNC_NEGATIVE:
    di_cta_vic_video_format_sync_polarity = 0;
pub const di_cta_vic_video_format_sync_polarity_DI_CTA_VIC_VIDEO_FORMAT_SYNC_POSITIVE:
    di_cta_vic_video_format_sync_polarity = 1;
#[doc = " CTA video format sync pulse polarity."]
pub type di_cta_vic_video_format_sync_polarity = ::std::os::raw::c_uint;
#[doc = " A CTA-861 video format, defined in section 4."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_cta_vic_video_format {
    pub vic: di_cta_vic,
    pub h_active: i32,
    pub v_active: i32,
    pub h_front: i32,
    pub v_front: i32,
    pub h_sync: i32,
    pub v_sync: i32,
    pub h_back: i32,
    pub v_back: i32,
    pub h_sync_polarity: di_cta_vic_video_format_sync_polarity,
    pub v_sync_polarity: di_cta_vic_video_format_sync_polarity,
    pub pixel_clock_hz: i64,
    pub interlaced: bool,
    pub picture_aspect_ratio: di_cta_vic_video_format_picture_aspect_ratio,
}
#[test]
fn bindgen_test_layout_di_cta_vic_video_format() {
    const UNINIT: ::std::mem::MaybeUninit<di_cta_vic_video_format> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<di_cta_vic_video_format>(),
        64usize,
        concat!("Size of: ", stringify!(di_cta_vic_video_format))
    );
    assert_eq!(
        ::std::mem::align_of::<di_cta_vic_video_format>(),
        8usize,
        concat!("Alignment of ", stringify!(di_cta_vic_video_format))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).vic) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(vic)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_active) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(h_active)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_active) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(v_active)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_front) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(h_front)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_front) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(v_front)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_sync) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(h_sync)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_sync) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(v_sync)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_back) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(h_back)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_back) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(v_back)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_sync_polarity) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(h_sync_polarity)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_sync_polarity) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(v_sync_polarity)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pixel_clock_hz) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(pixel_clock_hz)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).interlaced) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(interlaced)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).picture_aspect_ratio) as usize - ptr as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(di_cta_vic_video_format),
            "::",
            stringify!(picture_aspect_ratio)
        )
    );
}
extern "C" {
    #[doc = " Get a CTA-861 video format from a CTA VIC.\n\n Returns NULL if the CTA VIC is unknown."]
    pub fn di_cta_vic_video_format_from_vic(vic: di_cta_vic) -> *const di_cta_vic_video_format;
}
extern "C" {
    #[doc = " Get a CTA VIC from a CTA-861 video format.\n\n Returns 0 if the video format is unknown."]
    pub fn di_cta_vic_video_format_to_vic(format: *const di_cta_vic_video_format) -> di_cta_vic;
}
