/* automatically generated by rust-bindgen 0.68.1 */

#[doc = " DisplayID v2 data structure."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_displayid2 {
    _unused: [u8; 0],
}
extern "C" {
    #[doc = " Get the DisplayID v2 revision."]
    pub fn di_displayid2_get_revision(displayid2: *const di_displayid2) -> ::std::os::raw::c_int;
}
#[doc = " A DisplayID v2 data block."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_displayid2_data_block {
    _unused: [u8; 0],
}
extern "C" {
    #[doc = " Get DisplayID v2 data blocks.\n\n The returned array is NULL-terminated."]
    pub fn di_displayid2_get_data_blocks(
        displayid2: *const di_displayid2,
    ) -> *const *const di_displayid2_data_block;
}
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_EXTENSION : di_displayid2_product_primary_use_case = 0 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_TEST:
    di_displayid2_product_primary_use_case = 1;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_GENERIC:
    di_displayid2_product_primary_use_case = 2;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_TV:
    di_displayid2_product_primary_use_case = 3;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_DESKTOP_PRODUCTIVITY : di_displayid2_product_primary_use_case = 4 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_DESKTOP_GAMING : di_displayid2_product_primary_use_case = 5 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_PRESENTATION : di_displayid2_product_primary_use_case = 6 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_HMD_VR:
    di_displayid2_product_primary_use_case = 7;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_HMD_AR:
    di_displayid2_product_primary_use_case = 8;
#[doc = " Product primary use case identifier, defined in table 2-3."]
pub type di_displayid2_product_primary_use_case = ::std::os::raw::c_uint;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_PRODUCT_ID:
    di_displayid2_data_block_tag = 32;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_DISPLAY_PARAMS:
    di_displayid2_data_block_tag = 33;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_TYPE_VII_TIMING:
    di_displayid2_data_block_tag = 34;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_TYPE_VIII_TIMING:
    di_displayid2_data_block_tag = 35;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_TYPE_IX_TIMING:
    di_displayid2_data_block_tag = 36;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_DYN_TIMING_RANGE_LIMITS:
    di_displayid2_data_block_tag = 37;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_DISPLAY_INTERFACE_FEATURES:
    di_displayid2_data_block_tag = 38;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_STEREO_DISPLAY_INTERFACE:
    di_displayid2_data_block_tag = 39;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_TILED_DISPLAY_TOPO:
    di_displayid2_data_block_tag = 40;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_CONTAINERID:
    di_displayid2_data_block_tag = 41;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_TYPE_X_TIMING:
    di_displayid2_data_block_tag = 42;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_ADAPTIVE_SYNC:
    di_displayid2_data_block_tag = 43;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_ARVR_HMD:
    di_displayid2_data_block_tag = 44;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_ARVR_LAYER:
    di_displayid2_data_block_tag = 45;
pub const di_displayid2_data_block_tag_DI_DISPLAYID2_DATA_BLOCK_CTA861:
    di_displayid2_data_block_tag = 129;
#[doc = " DisplayID v2 data block tag."]
pub type di_displayid2_data_block_tag = ::std::os::raw::c_uint;
extern "C" {
    #[doc = " Get a DisplayID v2 data block tag."]
    pub fn di_displayid2_data_block_get_tag(
        data_block: *const di_displayid2_data_block,
    ) -> di_displayid2_data_block_tag;
}
extern "C" {
    #[doc = " Get the DisplayID v2 product primary use case."]
    pub fn di_displayid2_get_product_primary_use_case(
        displayid2: *const di_displayid2,
    ) -> di_displayid2_product_primary_use_case;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_cta_data_block {
    _unused: [u8; 0],
}
extern "C" {
    #[doc = " Get CTA data blocks from a DisplayID v2 CTA-861 data block.\n\n The returned array is NULL-terminated.\n\n Returns NULL if the data block tag isn't DI_DISPLAYID2_DATA_BLOCK_CTA861."]
    pub fn di_displayid2_data_block_get_cta_data_blocks(
        data_block: *const di_displayid2_data_block,
    ) -> *const *const di_cta_data_block;
}
