/* automatically generated by rust-bindgen 0.68.1 */

#[doc = " A HDMI Video Identification Code (VIC)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_hdmi_vic {
    pub code: u8,
}
#[test]
fn bindgen_test_layout_di_hdmi_vic() {
    const UNINIT: ::std::mem::MaybeUninit<di_hdmi_vic> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<di_hdmi_vic>(),
        1usize,
        concat!("Size of: ", stringify!(di_hdmi_vic))
    );
    assert_eq!(
        ::std::mem::align_of::<di_hdmi_vic>(),
        1usize,
        concat!("Alignment of ", stringify!(di_hdmi_vic))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).code) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic),
            "::",
            stringify!(code)
        )
    );
}
#[doc = " A HDMI video format, not to be confused with a CTA-861 video format."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_hdmi_vic_video_format {
    pub vic: di_hdmi_vic,
    pub h_active: i32,
    pub v_active: i32,
    pub h_front: i32,
    pub v_front: i32,
    pub h_sync: i32,
    pub v_sync: i32,
    pub h_back: i32,
    pub v_back: i32,
    pub pixel_clock_hz: i64,
}
#[test]
fn bindgen_test_layout_di_hdmi_vic_video_format() {
    const UNINIT: ::std::mem::MaybeUninit<di_hdmi_vic_video_format> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<di_hdmi_vic_video_format>(),
        48usize,
        concat!("Size of: ", stringify!(di_hdmi_vic_video_format))
    );
    assert_eq!(
        ::std::mem::align_of::<di_hdmi_vic_video_format>(),
        8usize,
        concat!("Alignment of ", stringify!(di_hdmi_vic_video_format))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).vic) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(vic)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_active) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(h_active)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_active) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(v_active)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_front) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(h_front)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_front) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(v_front)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_sync) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(h_sync)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_sync) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(v_sync)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_back) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(h_back)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v_back) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(v_back)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pixel_clock_hz) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(di_hdmi_vic_video_format),
            "::",
            stringify!(pixel_clock_hz)
        )
    );
}
extern "C" {
    #[doc = " Get a HDMI video format from a HDMI VIC.\n\n Returns NULL if the HDMI VIC is unknown."]
    pub fn di_hdmi_vic_video_format_from_vic(vic: di_hdmi_vic) -> *const di_hdmi_vic_video_format;
}
extern "C" {
    #[doc = " Get a HDMI VIC from a HDMI video format.\n\n Returns 0 if the video format is unknown."]
    pub fn di_hdmi_vic_video_format_to_vic(format: *const di_hdmi_vic_video_format) -> di_hdmi_vic;
}
